/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JComponent;

/**
 *
 * @author cesar
 */
public class TeamPanel extends javax.swing.JPanel {

    /**
     * Creates new form TeamPanel
     */
    public TeamPanel() {
        initComponents();
    }

    public void deshabilitar(){
    setOpaque(false); // Hacer el JPanel transparente
    resaltarJugador(0);
    repaint();
    }
    
    
    public void resaltarJugador(int index){
        this.labJugador1.setForeground(Color.black);
        this.labJugador2.setForeground(Color.black);
        this.labJugador3.setForeground(Color.black);
        this.labJugador4.setForeground(Color.black);
        switch(index){
            case 1->this.labJugador1.setForeground(Color.red);
            case 2->this.labJugador2.setForeground(Color.red);
            case 3->this.labJugador3.setForeground(Color.red);
            case 4->this.labJugador4.setForeground(Color.red);
        }
        
    }
    
    
    public void habilitar(){
    setOpaque(true); // Hacer el JPanel transparente
    repaint();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labEquipo = new javax.swing.JLabel();
        labJugador1 = new javax.swing.JLabel();
        labJugador2 = new javax.swing.JLabel();
        labJugador3 = new javax.swing.JLabel();
        labJugador4 = new javax.swing.JLabel();
        labFoto1 = new javax.swing.JLabel();
        labFoto2 = new javax.swing.JLabel();
        labFoto3 = new javax.swing.JLabel();
        labFoto4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(188, 201, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        labEquipo.setBackground(new java.awt.Color(45, 23, 224));
        labEquipo.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        labEquipo.setForeground(new java.awt.Color(255, 255, 255));
        labEquipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labEquipo.setText("EQUIPO");
        labEquipo.setOpaque(true);

        labJugador1.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        labJugador1.setForeground(new java.awt.Color(0, 0, 0));
        labJugador1.setText("Nombre Apellido");

        labJugador2.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        labJugador2.setForeground(new java.awt.Color(0, 0, 0));
        labJugador2.setText("Nombre Apellido");

        labJugador3.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        labJugador3.setForeground(new java.awt.Color(0, 0, 0));
        labJugador3.setText("Nombre Apellido");

        labJugador4.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        labJugador4.setForeground(new java.awt.Color(0, 0, 0));
        labJugador4.setText("Nombre Apellido");

        labFoto1.setForeground(new java.awt.Color(0, 0, 0));
        labFoto1.setText("foto");

        labFoto2.setForeground(new java.awt.Color(0, 0, 0));
        labFoto2.setText("foto");

        labFoto3.setForeground(new java.awt.Color(0, 0, 0));
        labFoto3.setText("foto");

        labFoto4.setForeground(new java.awt.Color(0, 0, 0));
        labFoto4.setText("foto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labJugador4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labJugador3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labJugador2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labJugador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labFoto1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labFoto2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labFoto3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labFoto4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
            .addComponent(labEquipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labFoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labFoto2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labFoto3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labJugador4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labFoto4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel labEquipo;
    public javax.swing.JLabel labFoto1;
    public javax.swing.JLabel labFoto2;
    public javax.swing.JLabel labFoto3;
    public javax.swing.JLabel labFoto4;
    public javax.swing.JLabel labJugador1;
    public javax.swing.JLabel labJugador2;
    public javax.swing.JLabel labJugador3;
    public javax.swing.JLabel labJugador4;
    // End of variables declaration//GEN-END:variables
}
